package modelo;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.TreeMap;

public class VentanaControl extends javax.swing.JPanel{
	/**
	 *
	 * @author carlo
	 */

	/**
	 * Creates new form Control
	 */
	public VentanaControl(HashMap<Integer, Nodo> nodos) {
		initComponents(nodos);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(HashMap<Integer, Nodo> nodos) {

		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jButton1 = new javax.swing.JButton();

		jLabel1.setText("Indica el aeropuerto en el que deseas comenzar la infección");
		
		String[] aeropuertos = new String[3334];
		int i = 0;
		TreeMap<String, Nodo> aeropuertosOrdenados = new TreeMap<String,Nodo>();
		for (Map.Entry<Integer, Nodo> entry : nodos.entrySet()) {
			aeropuertosOrdenados.put(entry.getValue().getInfo().getName(), 
					entry.getValue());
		}
		for (Entry<String, Nodo> entry : aeropuertosOrdenados.entrySet()) {
			aeropuertos[i] = entry.getKey();
			i+=1;
		}
		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(aeropuertos));

		jButton1.setText("COMENZAR INFECCIÓN");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(29, 29, 29).addComponent(jComboBox1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 258,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(170, 170, 170).addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 262,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(50, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(70, 70, 70).addComponent(jButton1).addContainerGap(104, Short.MAX_VALUE)));
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration

}
